name: Publish prereleased

on:
  release:
    types: [created]  
jobs:
  publish-npm:
    name: Publish prereleased
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Check Tag
      id: check-tag
      run: |
        if [[ "$RELEASE_VERSION" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(\-([a-zA-Z]+)(\.[0-9]+)?)?$ ]]; then
          echo ::set-env name=PREID::$(echo ${BASH_REMATCH[5]})
            printf 'Got %s, %s and %s\n' \
            "${BASH_REMATCH[1]}" "${BASH_REMATCH[4]}" "${BASH_REMATCH[5]}" 
        fi
        printf 'Got\n'
    - name: Test PREID
      run: |
        echo $PREID
        echo ${{ env.PREID }}
    - run: yarn install --frozen-lockfile
    - name: Publish to NPMJS
      run: yarn lerna publish -y --no-verify-access --canary --dist-tag "$PREID"     
