name: Publish prereleased

on:
  release:
    types: [prereleased]  
jobs:
  publish-npm:
    name: Publish prereleased
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Dump release name
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
