name: CI

on:
  push:
    branches:
    - master
jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: export NPM_TOKEN="${NPM_TOKEN}"
      - run: source ~/.profile
      - run: yarn lerna publish from-package -y --no-verify-access --registry https://registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
