name: CI

on:
  push:
    branches:
    - master
jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
        #token: '${{secrets.npm_token}}'
    - run: yarn install
    - run: yarn lerna publish from-package -y --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@slupekdevsandbox'
    - run: yarn lerna publish from-package -y --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
